# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(max_length=5)),
                ('end_time', models.IntegerField(max_length=5)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.CharField(max_length=20)),
                ('page_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lyrics',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.VideoPage'),
        ),
    ]
