# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
