# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170731_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyrics',
            old_name='page_id',
            new_name='videoPage',
        ),
    ]
